apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgress  # Ensure this is postgress
spec:
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: postgresql-repo
        namespace: postgress  # Ensure this matches the HelmRepository namespace
      version: 12.1.0
  interval: 1m
  values:
    global:
      postgresql:
        auth:
          username: admin
          password: admin@admin
          database: mydatabase

